# Generated by Django 3.0.7 on 2023-07-14 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fecha_nac',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_nacionalidad', to='subastas_redes.Pais'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pais_domicilio', to='subastas_redes.Pais'),
        ),
    ]
