# Generated by Django 3.0.7 on 2023-07-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0004_remove_user_vive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='website',
        ),
    ]
