# Generated by Django 3.0.7 on 2023-07-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0005_remove_tienda_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='titulo',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
