# Generated by Django 3.0.7 on 2023-07-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0006_auto_20230714_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='segundo_apellido',
        ),
        migrations.RemoveField(
            model_name='user',
            name='segundo_nombre',
        ),
    ]
