# Generated by Django 3.0.7 on 2023-07-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0008_auto_20230715_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo_puja',
        ),
    ]
