# Generated by Django 3.0.7 on 2023-07-15 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0010_auto_20230715_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ask',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subastas_redes.Tienda'),
            preserve_default=False,
        ),
    ]
