# Generated by Django 3.0.7 on 2023-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0011_auto_20230715_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ask',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='bid',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
