# Generated by Django 3.0.7 on 2023-07-19 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0014_auto_20230719_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_inicio',
        ),
    ]
