# Generated by Django 3.0.7 on 2023-07-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0016_producto_fecha_inicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fecha_nac',
        ),
    ]
