# Generated by Django 3.0.7 on 2023-07-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0017_remove_user_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
    ]
