# Generated by Django 3.0.7 on 2023-07-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subastas_redes', '0018_auto_20230719_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='total_manejo_envio',
        ),
    ]
